[lab]
target ansible_host={{ namespace.labLinuxHost }} ansible_user={{ secret('LAB_LINUX_USER') }} ansible_python_interpreter=/usr/bin/python3 ansible_ssh_private_key_file=id_ed25519 ansible_ssh_common_args='-o UserKnownHostsFile=known_hosts -o StrictHostKeyChecking=yes'
